dist: focal
language: python
python:
  - "3.7"
services:
  - docker
env:
  - PY_VER=3.6.8
  - PY_VER=3.7.3
  - PY_VER=3.8.6
  - PY_VER=3.9.0

install: "" # so travis doesn't do pip install requirements.txt
script:
  - docker build -f py.Dockerfile --build-arg MUJOCO_KEY=$MUJOCO_KEY --build-arg PYTHON_VER=$PY_VER -t gym-test .
  - docker run gym-test

deploy:
    provider: pypi
    username: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
        tags: true
        condition: $PY_VER = 3.6.8
